### ISSUE TITLE
Ability to create/update a variable with a single command

### ISSUE THREAD

**Issue by hanoii** [platformsh/legacy-cli#1031]
This is more a FR kind of how `vset` worked before. It's useful to have a single command that can take care of creating/updating a variable if it already exists.

I wonder if a -c[reate] can be added to `variable:update` or a -u[pdate] to `variable:create`, or both, or create a new command?

**Comment by hanoii** [comment]
Would like to bump this one to see if it's possible to add?

**Comment by pjcdawkins** [comment]
That definitely sounds like a good thing
