### ISSUE TITLE
Migrate check should follow symlinks

### ISSUE THREAD

**Issue by akalipetis** [platformsh/legacy-cli#1216]
If there's a symlink to the Platform.sh CLI, the new migrate check will get confused and prompt the user to delete the CLI.

Example reproduction output:

<details>

```console
➜  ~ platform auth:info
...
➜  ~ ln -s `which platform` ~/.local/bin/platform
➜  ~ platform auth:info

Warning: Both the Legacy (PHP) CLI and the New CLI are installed on your system.
To migrate fully, delete the Legacy CLI.

Remove the following file completely: /Users/akalipetis/.platformsh/bin/platform
This operation is safe and doesn't delete any data.

Do you want to remove this file now? [Y/n]
```

</details>

We should follow symlinks when checking for multiple binaries in the system.

**Comment by pjcdawkins** [comment]
@akalipetis so I guess we need to follow the symlink to check the paths are different, and also to check the thing we are deleting is not itself a symlink?

`realpath()` is probably our friend then

**Comment by TPXP** [comment]
This is what I faced in #1215 , feel free to close it as duplicate of this issue if you wish 😉

**Comment by akalipetis** [comment]
Closing as duplicate of #1215
