### ISSUE TITLE
Installing the phar file to /usr/local/bin fails "The directory is not writeable: /usr/local/bin"

### ISSUE THREAD

**Issue by jonpugh** [platformsh/legacy-cli#1276]
Disclosure: I did not read the install instructions. It's just a reflex to move phar files to /usr/local/bin, after so many years of drush and composer. 

## Problem
Installing the phar file to a global location fails to run:

```
$ platform
Checking for Platform.sh CLI updates (current version: 4.7.0)

                                                   
  [FilesystemException]                            
  The directory is not writeable: /usr/local/bin.                                                  
```

The phar executable expects the folder it is in to be writable.

Seems a little heavy handed?

Most apps I know of save stuff to home directory or /tmp.

I see that this method is "no longer supported", but having this logic seems a little weird.

Thanks!

**Comment by pjcdawkins** [comment]
Thanks this is definitely fixable - it's just the self-updating part, which isn't properly handling the not-writeable error

**Comment by pjcdawkins** [comment]
You're welcome to install it like this of course but it means it won't automatically check for updates. Possibly `sudo platform up` will work, to make it update manually, though I haven't tried that.
