### ISSUE TITLE
Flexible resources improvements with Git 25

### ISSUE THREAD

**Issue by nicogommen** [platformsh/legacy-cli#1384]
### resources:set

- Use the defaults coming from the API instead of the hard coded defaults.
- Add options to directly set the defaults or minimums. 
For example:
```
resources:set --size app:default,db:2 --disk *:minimum --instances *:3
resources:set --size *:default
```

---

### environment:merge

- If project has `sizing_api_enabled=true`
- Add new `resources-init` options to the merge command, to use the new resource initialization strategies.
```
--resources-init=child (default)
--resources-init=default
--resources-init=minimum
--resources-init=manual
```

---

### environment:branch

- If project has `sizing_api_enabled=true`
- Add new `resources-init` options to the branch command, to use the new resource initialization strategies.
```
--resources-init=parent (default)
--resources-init=default
--resources-init=minimum
--resources-init=manual
```

---

### environment:activate

- If project has `sizing_api_enabled=true`
- Add new `resources-init` options to the environment:activate command, to use the new resource initialization strategies.
```
--resources-init=parent (default)
--resources-init=default
--resources-init=minimum
--resources-init=manual
```

---

### backup:restore

- If project has `sizing_api_enabled=true`
- Add new `resources-init` options to the backup:restore command, to use the new resource initialization strategies.
```
--resources-init=parent (default)
--resources-init=default
--resources-init=minimum
--resources-init=manual
```

---

### resources:get

- Add an option (`--all`?) to be able to get all the resources of the project, for all environments.

---

### environment:synchronize

- If project has `sizing_api_enabled=true`
- Add possibility to sync the resources to the environment:sync command (in addition to the code and data).
```
upsun sync code data resources
```

**Comment by pjcdawkins** [comment]
The above PRs solve everything except

> Add an option (--all?) to be able to get all the resources of the project, for all environments.

which I have moved to a separate issue #1410
