### ISSUE TITLE
upsun integration:activities is missing in the exported md file for the doc

### ISSUE THREAD

**Issue by flovntp** [platformsh/legacy-cli#1439]
seems that `upsun integration:activities` is missing in the [CLI command reference](https://docs.upsun.com/administration/cli/reference.html)
What is missing on the CLI side for this command to be exported ?

**Comment by pjcdawkins** [comment]
The command is here

https://docs.upsun.com/administration/cli/reference.html#integrationactivitylist

So it's something to do with how the aliases are exported

**Comment by pjcdawkins** [comment]
Oh because the alias in question is a hidden one -

https://github.com/platformsh/legacy-cli/blob/e009a87025ddbbf7c54bef3a476085e2569a6117/src/Command/Integration/Activity/IntegrationActivityListCommand.php#L42

**Comment by pjcdawkins** [comment]
That's the PR if you want ^
