### ISSUE TITLE
Composer\Repository\RepositorySecurityException

### ISSUE THREAD

**Issue by jsacksick** [platformsh/legacy-cli#162]
[Composer\Repository\RepositorySecurityException]  
  The contents of http://packagist.org/p/platformsh/cli$0f86440a9915cc7f2f4e1  
  a900285f5ce64dc53794233a8e448e3c99622d0de1a.json do not match its signature  
  . This should indicate a man-in-the-middle attack. Try running composer aga  
  in and report this if you think it is a mistake.

**Comment by VijaySankhat** [comment]
Got same error...below is the detail for the error.

[Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/illuminate/pagination$47dc170ac3e8c4534e7d3ee39623a2cc8495821847914a59b1ec32dfc439a0c8.json do not match its signature
  . This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

**Comment by aireol** [comment]
How did you resolved this issue?

**Comment by devamit2018** [comment]
update your composer
https://getcomposer.org/download/ go through this linkand download composer setup.exe
