### ISSUE TITLE
problem when trying to run Platform CLI on Eshell ..

### ISSUE THREAD

**Issue by fenix011** [platformsh/legacy-cli#566]
I'm having a problem when trying to run Platform CLI on Eshell ... (running on Bash is fine )

> q: command not found

Aiming at being able to use both Eshell and Platform CLI ¿ does the latter need special formatting (as the TERM environment variable is "dumb"). ¿ Does it require special settings in the environment or path?

**Comment by pjcdawkins** [comment]
Sorry for the rather late reply (!) - does this still fail, and what particular command fails?

(and do you know of other Symfony Console applications that successfully support Eshell?)
